name: Build and Push Latest Model Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: dhanush789245/ml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

      # Step 4: Get Latest Model Version
      - name: Get Latest Model Version
        id: get_version
        run: |
          LATEST_VERSION=$(ls -1 models | sort -V | tail -n 1)
          echo "MODEL_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "Latest model version: $LATEST_VERSION"

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
          --build-arg MODEL_VERSION=$MODEL_VERSION \
          -t $IMAGE_NAME:$MODEL_VERSION \
          -t $IMAGE_NAME:latest .

      # Step 6: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$MODEL_VERSION
          docker push $IMAGE_NAME:latest

      - name: Update deployment.yaml with new version
        run: |
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$MODEL_VERSION|g" k8s/deployment.yaml

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update deployment.yaml to use model version $MODEL_VERSION"
          file_pattern: 'k8s/deployment.yaml'

