name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: dhanush789245/ml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Get Model Version
        id: version
        run: |
          LATEST_VERSION=$(ls -1 models | sort -V | tail -n 1)
          echo "MODEL_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        run: |
          docker build \
            --build-arg MODEL_VERSION=$MODEL_VERSION \
            -t $IMAGE_NAME:$MODEL_VERSION \
            -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$MODEL_VERSION
          docker push $IMAGE_NAME:latest

      - name: Update Deployment Version
        run: |
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$MODEL_VERSION|g" k8s/deployment.yaml

      - name: Auto-Commit Deployment Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update deployment to model version $MODEL_VERSION"
          file_pattern: 'k8s/deployment.yaml'
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        if: github.event_name == 'pull_request'
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
