name: Build and Push Latest Model Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: dhanush789245/ml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        persist-credentials: false # Ensure credentials are not reused
        fetch-depth: 0 # Fetch all history for accurate versioning

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Get Latest Model Version
      id: get_version
      run: |
        LATEST_VERSION=$(ls -1 models | sort -V | tail -n 1)
        echo "MODEL_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        echo "Latest model version: $LATEST_VERSION"

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg MODEL_VERSION=$MODEL_VERSION \
          -t $IMAGE_NAME:$MODEL_VERSION \
          -t $IMAGE_NAME:latest .

    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:$MODEL_VERSION
        docker push $IMAGE_NAME:latest

    - name: Update deployment.yaml with new version
      if: github.event_name == 'push'
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$MODEL_VERSION|g" k8s/deployment.yaml
        
        # Stage changes immediately to avoid unstaged changes during rebase
        git add k8s/deployment.yaml
        
        # Configure Git user details for commit and push
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Pull latest changes with rebase to avoid conflicts
        git pull origin main --rebase
        
        # Commit and push changes to the main branch
        git commit -m "Update deployment to use model version $MODEL_VERSION"
        git push origin HEAD:main

    - name: Update deployment.yaml with new version and push to PR branch
      if: github.event_name == 'pull_request'
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$MODEL_VERSION|g" k8s/deployment.yaml
        
        # Stage changes immediately to avoid unstaged changes during rebase
        git add k8s/deployment.yaml
        
        # Configure Git user details for commit and push
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Check out the pull request branch dynamically using github.head_ref
        git checkout ${{ github.head_ref }}
        
        # Pull latest changes with rebase to avoid conflicts on the PR branch
        git pull origin ${{ github.head_ref }} --rebase
        
        # Commit and push changes to the pull request branch
        git commit -m "Update deployment to use model version $MODEL_VERSION"
        git push origin HEAD:${{ github.head_ref }}
