name: Build and Push Latest Model Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: dhanush789245/ml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        persist-credentials: false 
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Get Latest Model Version
      id: get_version
      run: |
        LATEST_VERSION=$(ls -1 models | sort -V | tail -n 1)
        echo "MODEL_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        echo "Latest model version: $LATEST_VERSION"

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg MODEL_VERSION=$MODEL_VERSION \
          -t $IMAGE_NAME:$MODEL_VERSION \
          -t $IMAGE_NAME:latest .

    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:$MODEL_VERSION
        docker push $IMAGE_NAME:latest

    - name: Update deployment.yaml with new version
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$MODEL_VERSION|g" k8s/deployment.yaml

    - name: Commit and Push Changes to Main Branch
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git pull origin main --rebase # Fetch latest changes and rebase
        git add k8s/deployment.yaml
        git commit -m "Update deployment to use model version $MODEL_VERSION"
        git push origin HEAD:main

    - name: Commit and Push Changes to PR Branch
      if: github.event_name == 'pull_request'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout ${{ github.head_ref }}
        git pull origin ${{ github.head_ref }} --rebase # Fetch latest changes and rebase
        git add k8s/deployment.yaml
        git commit -m "Update deployment to use model version $MODEL_VERSION"
        git push origin HEAD:${{ github.head_ref }}
